// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Db;

#nullable disable

namespace Shop.Db.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20260215160049_ImgCategories")]
    partial class ImgCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Db.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpYear")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Cards", t =>
                        {
                            t.HasCheckConstraint("CK_CardNumber_Length", "LEN(CardNumber) = 16");

                            t.HasCheckConstraint("CK_Cvv_Length", "LEN(Cvv) = 3");
                        });
                });

            modelBuilder.Entity("Shop.Db.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "img/categories/крупы.jpg",
                            Name = "Крупы"
                        },
                        new
                        {
                            Id = 2,
                            Image = "img/categories/мучное.jpg",
                            Name = "Мучное"
                        },
                        new
                        {
                            Id = 3,
                            Image = "img/categories/овощи.jpg",
                            Name = "Овощи"
                        },
                        new
                        {
                            Id = 4,
                            Image = "img/categories/фрукты.jpg",
                            Name = "Фрукты и ягоды"
                        },
                        new
                        {
                            Id = 5,
                            Image = "img/categories/молочные_продукты.jpg",
                            Name = "Молочные продукты"
                        },
                        new
                        {
                            Id = 6,
                            Image = "img/categories/белковые_продукты.jpg",
                            Name = "Белковые продукты"
                        },
                        new
                        {
                            Id = 7,
                            Image = "img/categories/алкоголь.jpg",
                            Name = "Алкоголь"
                        });
                });

            modelBuilder.Entity("Shop.Db.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shop.Db.Entities.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Shop.Db.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 40,
                            Expiration = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/гречка.jpg",
                            Name = "Гречка",
                            Price = 100m,
                            PurchasePrice = 50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 40,
                            Expiration = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/рис.jpg",
                            Name = "Рис",
                            Price = 50m,
                            PurchasePrice = 30m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Count = 40,
                            Expiration = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/овсянка.jpg",
                            Name = "Овсяка",
                            Price = 40m,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Count = 30,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/хлеб_белый.jpg",
                            Name = "Хлеб белый",
                            Price = 40m,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Count = 30,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/хлеб_черный.jpg",
                            Name = "Хлеб черный",
                            Price = 40m,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Count = 50,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/булочки.jpg",
                            Name = "Булочки",
                            Price = 30m,
                            PurchasePrice = 15m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Count = 30,
                            Expiration = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/огурцы.jpg",
                            Name = "Огурцы",
                            Price = 50m,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Count = 30,
                            Expiration = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/помидоры.jpg",
                            Name = "Помидоры",
                            Price = 70m,
                            PurchasePrice = 40m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Count = 50,
                            Expiration = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/картошка.jpg",
                            Name = "Картошка",
                            Price = 45m,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Count = 50,
                            Expiration = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/лук.jpg",
                            Name = "Лук",
                            Price = 25m,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Count = 40,
                            Expiration = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/яблоки.jpg",
                            Name = "Яблоки",
                            Price = 30m,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Count = 40,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/бананы.jpg",
                            Name = "Бананы",
                            Price = 45m,
                            PurchasePrice = 25m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Count = 40,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/бананы.jpg",
                            Name = "Бананы",
                            Price = 45m,
                            PurchasePrice = 25m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Count = 50,
                            Expiration = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/мандарины.jpg",
                            Name = "Мандарины",
                            Price = 70m,
                            PurchasePrice = 45m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Count = 50,
                            Expiration = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/виноград.jpg",
                            Name = "Виноград",
                            Price = 70m,
                            PurchasePrice = 45m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Count = 20,
                            Expiration = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/молоко.jpg",
                            Name = "Молоко",
                            Price = 150m,
                            PurchasePrice = 70m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Count = 20,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/творог.jpg",
                            Name = "Творог",
                            Price = 120m,
                            PurchasePrice = 60m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Count = 20,
                            Expiration = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/сметана.jpg",
                            Name = "Сметана",
                            Price = 100m,
                            PurchasePrice = 50m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Count = 30,
                            Expiration = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/сыр.jpg",
                            Name = "Сыр",
                            Price = 150m,
                            PurchasePrice = 75m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            Count = 15,
                            Expiration = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/курица.jpg",
                            Name = "Курица",
                            Price = 250m,
                            PurchasePrice = 150m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Count = 15,
                            Expiration = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/свинина.jpg",
                            Name = "Свинина",
                            Price = 300m,
                            PurchasePrice = 200m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Count = 15,
                            Expiration = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/рыба.jpg",
                            Name = "Рыба",
                            Price = 300m,
                            PurchasePrice = 200m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Count = 200,
                            Expiration = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/яйца.jpg",
                            Name = "Яйца",
                            Price = 100m,
                            PurchasePrice = 50m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Count = 20,
                            Expiration = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/вино.jpg",
                            Name = "Вино",
                            Price = 1000m,
                            PurchasePrice = 500m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Count = 20,
                            Expiration = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/шампанское.jpg",
                            Name = "Шампанское",
                            Price = 800m,
                            PurchasePrice = 400m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Count = 20,
                            Expiration = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "img/products/коньяк.jpg",
                            Name = "Коньяк",
                            Price = 1500m,
                            PurchasePrice = 700m
                        });
                });

            modelBuilder.Entity("Shop.Db.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Money")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop.Db.Entities.Card", b =>
                {
                    b.HasOne("Shop.Db.Entities.User", null)
                        .WithOne("Card")
                        .HasForeignKey("Shop.Db.Entities.Card", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Db.Entities.Order", b =>
                {
                    b.HasOne("Shop.Db.Entities.User", null)
                        .WithOne("Order")
                        .HasForeignKey("Shop.Db.Entities.Order", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Db.Entities.OrderProduct", b =>
                {
                    b.HasOne("Shop.Db.Entities.Order", null)
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Db.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Db.Entities.Product", b =>
                {
                    b.HasOne("Shop.Db.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Db.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Db.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Shop.Db.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Shop.Db.Entities.User", b =>
                {
                    b.Navigation("Card");

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
